/**
 * Post-build: append Cloudflare Early Hints (HTTP 103) Link headers to
 * dist/_headers. CF Pages auto-promotes Link: <X>; rel=preload to a 103
 * Early Hints response sent during origin think-time, so the browser
 * begins fetching CSS before the HTML body arrives.
 *
 * Reference: https://developers.cloudflare.com/pages/configuration/early-hints/
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const distDir = './dist';
const headersPath = join(distDir, '_headers');
const astroDir = join(distDir, '_astro');

const cssFiles = readdirSync(astroDir).filter(f => f.endsWith('.css'));

// JSONCraft: every page imports tools.HASH.css; home pages also import
// HomeLanding.HASH.css. Preload both on home, only tools elsewhere.
const toolsCss = cssFiles.find(f => /^tools\..*\.css$/.test(f));
const homeLandingCss = cssFiles.find(f => /^HomeLanding\..*\.css$/.test(f));

if (!toolsCss) {
  console.log('[early-hints] no tools.*.css found in _astro/, skipping');
  process.exit(0);
}

const linkTools = `Link: </_astro/${toolsCss}>; rel=preload; as=style`;
const linkHomeLanding = homeLandingCss
  ? `Link: </_astro/${homeLandingCss}>; rel=preload; as=style`
  : null;

const earlyHintsBlock = [
  '# Cloudflare Early Hints (HTTP 103) — auto-generated by',
  '# scripts/early-hints.mjs after each build. Preloads the CSS bundle',
  '# during origin think-time, so cold-visit FCP/LCP improve without',
  '# inflating HTML payload. CF only emits 103 on HTML responses.',
  '/*',
  `  ${linkTools}`,
  '',
  ...(linkHomeLanding ? ['/', `  ${linkTools}`, `  ${linkHomeLanding}`, ''] : []),
  ...(linkHomeLanding ? ['/es/', `  ${linkTools}`, `  ${linkHomeLanding}`, ''] : []),
  '',
].join('\n');

const existing = readFileSync(headersPath, 'utf-8');
writeFileSync(headersPath, earlyHintsBlock + existing);
console.log(`[early-hints] prepended Link headers to dist/_headers`);
console.log(`[early-hints]   global: ${toolsCss}`);
if (homeLandingCss) console.log(`[early-hints]   home/es: + ${homeLandingCss}`);
